environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm run format:ci
  - npm run lint:ci
  - npm run test:ci

# Don't actually build.
build: off
